apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: adiboy/petclinic:latest
        ports:
        - containerPort: 8080
          name: petclinic-port
        env:
        - name: SPRING_DATASOURCE_USERNAME
          value: "petclinic"
          # valueFrom:
          #   secretKeyRef:
          #     name: mysql-secret
          #     key: mysql-user
        - name: SPRING_DATASOURCE_PASSWORD
          value: "petclinic"
          # valueFrom:
          #   secretKeyRef:
          #     name: mysql-secret
          #     key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  selector:
      app: petclinic
  ports:
  - port: 8080
    protocol: TCP
    targetPort: petclinic-port
  